import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    { type: 'autogenerated', dirName: '.' },
    {
      type: 'category',
      label: 'Custom Sidebar Category',
      description: 'This category is defined directly in the sidebar config',
      link: {
        type: 'generated-index',
        title: 'Custom Category Index',
        description: 'This is a custom category index page generated from sidebar configuration. It demonstrates how the LLMs plugin handles category pages created through sidebar config.',
        keywords: ['sidebar', 'category', 'custom'],
      },
      items: [
        {
          type: 'doc',
          id: 'intro',
          label: 'Introduction (from sidebar)',
        },
        {
          type: 'doc',
          id: 'tutorial-basics/create-a-document',
          label: 'Creating Documents (from sidebar)',
        },
      ],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
