name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-and-type-check:
    name: Lint and Type Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js and Dependencies
        uses: ./.github/actions/setup

      - name: Build packages
        run: yarn run build:packages

      - name: Check code formatting
        run: yarn run format:check

      - name: Lint
        run: yarn run lint

      - name: Type check
        run: yarn run type-check

  test-plugins:
    name: Test Plugins
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js and Dependencies
        uses: ./.github/actions/setup

      - name: Build packages
        run: yarn run build:packages

      - name: Test packages
        run: yarn run test

  test-website:
    name: Test Website Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js and Dependencies
        uses: ./.github/actions/setup

      - name: Build website
        run: yarn run build:website

  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js and Dependencies
        uses: ./.github/actions/setup

      - name: Run security audit
        run: yarn audit --groups dependencies
