name: Test Matrix

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  schedule:
    # Run weekly on Sunday at 2 AM UTC
    - cron: '0 2 * * 0'

jobs:
  test-matrix:
    name: Test (Node ${{ matrix.node-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node-version: ['18', '20', '22']
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          # Test with different yarn versions
          - node-version: '20'
            os: ubuntu-latest
            yarn-version: '1.22.19'
          - node-version: '20'
            os: ubuntu-latest
            yarn-version: '4.0.2'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Setup specific Yarn version
        if: matrix.yarn-version
        run: |
          corepack enable
          corepack prepare yarn@${{ matrix.yarn-version }} --activate

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build packages
        run: yarn run build:packages

      - name: Test packages
        run: yarn run test

      - name: Lint code
        run: yarn run lint

      - name: Type check
        run: yarn run type-check

      - name: Test website build
        run: yarn run build:website

  test-docusaurus-versions:
    name: Test with Docusaurus ${{ matrix.docusaurus-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        docusaurus-version: ['3.0.0', '3.5.0', '3.8.0']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Update Docusaurus version
        run: |
          cd website
          yarn add @docusaurus/core@${{ matrix.docusaurus-version }} @docusaurus/preset-classic@${{ matrix.docusaurus-version }}

      - name: Build packages
        run: yarn run build:packages

      - name: Test website build with Docusaurus ${{ matrix.docusaurus-version }}
        run: yarn run build:website
